title: jutor # 博客名称
description: hi # 博客简介
url: https://github.com/Eman-BK-201/username.github.io # 博客url
template: acyort-templates-donob-plus
menu:
  Archives: /archives/
  Tags: /tags/
repository: Eman-BK-201/blog-config # 写 issues 的项目
public: public
timezone: Asia/Shanghai
plugins:
  - acyort-plugin-fetch-issues
  - acyort-donob-renderer
